# Generated by Django 5.1.6 on 2025-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='diary/picture/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(max_length=2000, verbose_name='本文'),
        ),
    ]
